### ISSUE TITLE
App doesn't work on a fresh Debian 8/ Yunohost 2.4 install

### ISSUE THREAD

**Issue by maniackcrudelis** [kemenaran/mattermost_ynh#10]
Hello

Your app failed to install.
I've mainly an error with mysql version. Even if you inform on working version of mysql, this is a blocking error on fresh Yunohost install.

See the log for more information:
http://jenkins-ci-arm.noho.st/jenkins/logs/github.com_kemenaran_mattermost_ynh.log

So, your app will be decreased at Notworking status untill these errors be corrected.

**Comment by kemenaran** [comment]
@maniackcrudelis thanks for your report. I'll try to have a look on a fresh Yunohost install.

(By the way, do you know of any testing advices for Yunohost apps? Or examples of apps using CI and Dockerfiles to write automatic tests?)

**Comment by maniackcrudelis** [comment]
Hello kemenaran

You may use [package check](https://github.com/YunoHost/package_check) to run many test on your package before release a new version.
Our CI instance use this set of unit test.

**Comment by kemenaran** [comment]
@maniackcrudelis I fixed the installation on a fresh Yunohost installation (tested locally using Vagrant). 4b2890ba1dbd5c3070477b30ec2525399b0c7b96

A CI run would be great to confirm this is still working – but it seems the Jenkins job for mattermost_ynh was deleted. Is it possible to reconfigure it on http://jenkins-ci-arm.noho.st?

**Comment by maniackcrudelis** [comment]
Yes, the job on jenkins was removed, because your app has moved to "notworking".

If you are sure your app is now working, open a pull request [here](https://github.com/YunoHost/apps/blob/master/community.json) to move it to "working".

**Comment by kemenaran** [comment]
@maniackcrudelis will do. Thanks for the advice.
