### ISSUE TITLE
Signing up for Security Bulletin mailing list

### ISSUE THREAD

**Issue by jasonblais** [kemenaran/mattermost_ynh#14]
Hey @kemenaran , 

Just letting you know that we have a new [Security Bulletin mailing list](http://eepurl.com/cAl5Rv) and I encourage you to sign up for it as well.

This mailing list will receive an email about a new Mattermost security release so that installers can update to that new version.

**Comment by kemenaran** [comment]
I just signed up. @jasonblais thanks for the hint.
