### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by JonasAllenCodes** [kemenaran/mattermost_ynh#3]
I have the current up to date versions of Debian and YUNoHost installed. This is what the current version of MySQL YUNoHost uses for MySQL "mysql  Ver 15.1 Distrib 10.0.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2"(What I get when I run "mysql --version"). When I try to install this app I get this error message, "Error: Requirements are not met, the package mysql-common (5.5.49-0+deb8u1) must be >= 5.6". What can we do to fix this? I would love to use Mattermost on my YUNoHost server.

**Comment by ultimate62** [comment]
Hello
I have the same problem !
Could you please help us !
Best regrads

**Comment by lyrz** [comment]
Hello, same problem.
I found a way to upgrade Mariadb to v 10.1 (which also upgrade mysql-common) by adding repositories for it.
I just followed the beginning of this tutorial : http://www.tecmint.com/install-mariadb-in-debian/. I had a gpg key verification pb solved with https://stackoverflow.com/questions/1139127/how-to-trust-a-apt-repository-debian-apt-get-update-error-public-key-is-not-av .
Then I used system update in Yunohost and it upgraded Mariadb.
The mysql-common issue disappeared but I'm still stuck as Mattermost seems to require a x86_64 platform to install.
I'm not sure if this Mariadb upgrade complies with Yunohost stability, I can just say I did it on my test platform and upgrade didn't break my install.
I'm testing Yunohost 2.4.0.7 on a Soekris net5501. (Installed debian Jessie on it with pxe boot)
Hope this can help other Yunohost testers :-)

**Comment by nico7337** [comment]
Hello,
Same problem and quite same way out but I used official Mariadb repository instead. Everything is explaned here : https://downloads.mariadb.org/mariadb/repositories/#distro_release=jessie--jessie&mirror=cnrs&distro=Debian&version=10.1
Work well for me, Mariadb upgrade to 10.1 et Mattermost is ok to install.

**Comment by kemenaran** [comment]
I just removed the dependency to MySQL, and allowed MariaDB to be used as a DB backend (4b2890b). This should allow both MySQL > 5.6 and MariaDB > 10 to be used, and should fix the package not installing on fresh Debian 8 installations.
