### ISSUE TITLE
Propose updating to Mattermost 3.5

### ISSUE THREAD

**Issue by jasonblais** [kemenaran/mattermost_ynh#6]
Hey @kemenaran, 

Just wanted to inform you that Mattermost 3.5 release has been cut.

The new release contains security updates and several API changes - you can [view the full changelog for Mattermost 3.5 here](https://docs.mattermost.com/administration/changelog.html#release-v3-5-0) and [find download links with hash numbers here](https://pre-release.mattermost.com/core/pl/9ye3kypwpfdqdyxxh9wwqc9qpe)

Wondering if you'd like to help update the Yunohost Installer to be compatible with Mattermost 3.5?

If you do update, please consider tweeting about it, which we can then retweet for greater reach.

Also, feel free to join the [Mattermost Installers community channel](https://pre-release.mattermost.com/core/channels/installers-and-images) for latest news relevant for installer owners.

**Comment by kemenaran** [comment]
Sure ; fixed with https://github.com/kemenaran/mattermost_ynh/commit/ea532f0cab17db0730814eab75f32494e3eafff7

Thanks for the heads-up! And also keeping Mattermost upgrade process smooth and automatic surely helps maintainers a lot: I just had to change the version number :)

**Comment by jasonblais** [comment]
Nice! Glad to hear :)
